CREATE TABLE workspaces (
  id bigint NOT NULL AUTO_INCREMENT,
  name varchar(120) NOT NULL,
  description text DEFAULT NULL,
  workspace_type enum('PERSONAL','TEAM','SERVICE') NOT NULL,
  owner_id bigint NOT NULL,
  created_by bigint NOT NULL,
  is_active bit(1) DEFAULT 1,
  is_locked bit(1) DEFAULT 0,
  lock_reason varchar(500) DEFAULT NULL,
  locked_by bigint DEFAULT NULL,
  bot_access_enabled bit(1) DEFAULT 0,
  created_at datetime(6) DEFAULT NULL,
  updated_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY FK_workspaces_owner (owner_id),
  KEY FK_workspaces_created_by (created_by),
  KEY FK_workspaces_locked_by (locked_by),
  CONSTRAINT FK_workspaces_owner FOREIGN KEY (owner_id) REFERENCES users (id),
  CONSTRAINT FK_workspaces_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT FK_workspaces_locked_by FOREIGN KEY (locked_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workspace_members (
  id bigint NOT NULL AUTO_INCREMENT,
  workspace_id bigint NOT NULL,
  user_id bigint NOT NULL,
  role enum('OWNER','ADMIN','EDITOR','VIEWER','SERVICE') NOT NULL,
  invited_by bigint DEFAULT NULL,
  created_at datetime(6) DEFAULT NULL,
  updated_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY UK_workspace_members_workspace_user (workspace_id, user_id),
  KEY FK_workspace_members_user (user_id),
  KEY FK_workspace_members_invited_by (invited_by),
  CONSTRAINT FK_workspace_members_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id),
  CONSTRAINT FK_workspace_members_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT FK_workspace_members_invited_by FOREIGN KEY (invited_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workspace_folders (
  id bigint NOT NULL AUTO_INCREMENT,
  workspace_id bigint NOT NULL,
  parent_folder_id bigint DEFAULT NULL,
  name varchar(180) NOT NULL,
  created_by bigint NOT NULL,
  is_deleted bit(1) DEFAULT 0,
  is_locked bit(1) DEFAULT 0,
  lock_reason varchar(500) DEFAULT NULL,
  locked_by bigint DEFAULT NULL,
  bot_access_enabled bit(1) DEFAULT 0,
  created_at datetime(6) DEFAULT NULL,
  updated_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY FK_workspace_folders_workspace (workspace_id),
  KEY FK_workspace_folders_parent (parent_folder_id),
  KEY FK_workspace_folders_created_by (created_by),
  KEY FK_workspace_folders_locked_by (locked_by),
  CONSTRAINT FK_workspace_folders_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id),
  CONSTRAINT FK_workspace_folders_parent FOREIGN KEY (parent_folder_id) REFERENCES workspace_folders (id),
  CONSTRAINT FK_workspace_folders_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT FK_workspace_folders_locked_by FOREIGN KEY (locked_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workspace_files (
  id bigint NOT NULL AUTO_INCREMENT,
  workspace_id bigint NOT NULL,
  folder_id bigint DEFAULT NULL,
  display_name varchar(255) NOT NULL,
  current_storage_name varchar(255) NOT NULL,
  mime_type varchar(160) DEFAULT NULL,
  file_size bigint DEFAULT NULL,
  current_version int DEFAULT NULL,
  source_type enum('USER','BOT','SERVICE') NOT NULL,
  source_bot_id bigint DEFAULT NULL,
  created_by bigint NOT NULL,
  is_deleted bit(1) DEFAULT 0,
  is_locked bit(1) DEFAULT 0,
  lock_reason varchar(500) DEFAULT NULL,
  locked_by bigint DEFAULT NULL,
  bot_access_enabled bit(1) DEFAULT 0,
  created_at datetime(6) DEFAULT NULL,
  updated_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY FK_workspace_files_workspace (workspace_id),
  KEY FK_workspace_files_folder (folder_id),
  KEY FK_workspace_files_source_bot (source_bot_id),
  KEY FK_workspace_files_created_by (created_by),
  KEY FK_workspace_files_locked_by (locked_by),
  CONSTRAINT FK_workspace_files_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id),
  CONSTRAINT FK_workspace_files_folder FOREIGN KEY (folder_id) REFERENCES workspace_folders (id),
  CONSTRAINT FK_workspace_files_source_bot FOREIGN KEY (source_bot_id) REFERENCES bot_configs (id),
  CONSTRAINT FK_workspace_files_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT FK_workspace_files_locked_by FOREIGN KEY (locked_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workspace_file_versions (
  id bigint NOT NULL AUTO_INCREMENT,
  file_id bigint NOT NULL,
  version_number int NOT NULL,
  storage_name varchar(255) NOT NULL,
  original_name varchar(255) NOT NULL,
  mime_type varchar(160) DEFAULT NULL,
  file_size bigint DEFAULT NULL,
  checksum_sha256 varchar(64) DEFAULT NULL,
  version_note varchar(500) DEFAULT NULL,
  uploaded_by bigint NOT NULL,
  uploaded_by_bot bigint DEFAULT NULL,
  created_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY UK_workspace_file_versions_file_version (file_id, version_number),
  KEY FK_workspace_file_versions_uploaded_by (uploaded_by),
  KEY FK_workspace_file_versions_uploaded_by_bot (uploaded_by_bot),
  CONSTRAINT FK_workspace_file_versions_file FOREIGN KEY (file_id) REFERENCES workspace_files (id),
  CONSTRAINT FK_workspace_file_versions_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id),
  CONSTRAINT FK_workspace_file_versions_uploaded_by_bot FOREIGN KEY (uploaded_by_bot) REFERENCES bot_configs (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workspace_permissions (
  id bigint NOT NULL AUTO_INCREMENT,
  workspace_id bigint NOT NULL,
  resource_type enum('WORKSPACE','FOLDER','FILE') NOT NULL,
  resource_id bigint DEFAULT NULL,
  principal_type enum('USER','BOT') NOT NULL,
  principal_id bigint NOT NULL,
  access_level enum('NONE','VIEW','EDIT','MANAGE') NOT NULL,
  created_by bigint NOT NULL,
  created_at datetime(6) DEFAULT NULL,
  updated_at datetime(6) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY IDX_workspace_permissions_principal (principal_type, principal_id),
  KEY IDX_workspace_permissions_resource (workspace_id, resource_type, resource_id),
  CONSTRAINT FK_workspace_permissions_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id),
  CONSTRAINT FK_workspace_permissions_created_by FOREIGN KEY (created_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
